name: Release

on:
  workflow_dispatch: # Manually triggered action

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: ".tar.gz"
            system_name: "linux"
          - os: macos-latest
            extension: ".tar.gz"
            system_name: "macos"
          - os: windows-latest
            extension: ".zip"
            system_name: "windows"

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Rust environment
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Build Rust backend
      - name: Build Rust backend
        run: cargo build --release

      # Build frontend (npm)
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          mv build ../

      # Package both Rust backend and frontend build results
      - name: Package build and backend
        run: |
          mkdir output
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell Compress-Archive -Path target/release,url_balancing.exe build -DestinationPath ./output/url_balancing_${{ matrix.system_name }}${{ matrix.extension }}
          else
            tar -czvf ./output/url_balancing_${{ matrix.system_name }}${{ matrix.extension }} -C target/release url_balancing -C ../../ build
          fi

      # Create a new GitHub release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag_name: "v1.0.0" # Can dynamically set version if needed
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
